version: "2"

volumes:
  node_modules:

services:
  npm:
    extends:
      file: docker-shared.yml
      service: app
    command: npm install

  test_unit:
    extends:
      file: docker-shared.yml
      service: app
    command: npm run test:unit

  test_acceptance:
    extends:
      file: docker-shared.yml
      service: app
    environment:
      REDIS_HOST: redis
      MONGO_URL: "mongodb://mongo/sharelatex"
      SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
    depends_on:
      - redis
      - mongo
    command: npm run start

  redis:
    image: redis

  mongo:
    image: mongo:3.4.6
