version: "2"

# We mount all the directories explicitly so that we are only mounting
# the coffee directories, so that the compiled js is only written inside
# the container, and not back to the local filesystem, where it would be
# root owned, and conflict with working outside of the container.

services:
  app:
    image: node:6.9.5
    volumes:
      - ./package.json:/app/package.json
      - ./npm-shrinkwrap.json:/app/npm-shrinkwrap.json
      - node_modules:/app/node_modules
      - ./bin:/app/bin
      - ./public/coffee:/app/public/coffee:ro
      - ./public/js/ace-1.2.5:/app/public/js/ace-1.2.5
      - ./app.coffee:/app/app.coffee:ro
      - ./app/coffee:/app/app/coffee:ro
      - ./app/templates:/app/app/templates:ro
      - ./app/views:/app/app/views:ro
      - ./config:/app/config
      - ./test/unit/coffee:/app/test/unit/coffee:ro
      - ./test/unit_frontend/coffee:/app/test/unit_frontend/coffee:ro
      - ./test/acceptance/coffee:/app/test/acceptance/coffee:ro
      - ./test/acceptance/files:/app/test/acceptance/files:ro
      - ./test/smoke/coffee:/app/test/smoke/coffee:ro
      MODULE_VOLUMES
    working_dir: /app
